### ISSUE TITLE
[Project]: "initfs key needs to be 16 bytes long"

### ISSUE THREAD

**Issue by AdrianFerrer1** [FrostyToolsuite/FrostyToolsuite#28]
### Please describe your issue

I'm getting that message when I try to run Frosty CLI passing BF2042 exe path and then \Data\initfs_Win32
Also if I try running FrostyEditor adding the exe path and then clicking select, the program crashes and closes

I dont really know what I'm doing tbh I just wanted to rip some model for a personal project

### Were you using the Editor or the Mod Manager?

Editor

### Which version of the Editor/Mod Manager are you using ?

latest

### Has Frosty worked for you before? If so, did anything change ?

No

### Do you have a cracked/pirated version of the game?

No

### Have you extracted all of the zip's contents (files and folders) into an empty folder?

Yes

### Are you using FrostyFix or DatapathFix to fix launching if you didn't purchase the game on Origin?

No

### Which game(s) are you trying to mod?

Battlefield 2042

### Which operating system version are you using?

W11

### Please provide a breakdown of the steps performed to produce the issue

run FrostyEditor
paste exe path
paste initfs path

### Please share the FULL error message

initfs key needs to be 16 bytes long

### If you're using the Mod Manager, have you tried applying only one mod? Did it work?

N/A

### If you're using the Mod Manager, please list the mods you're applying with

-

### Did you modify, remove, or add any plugins?

No

**Comment by wannkunstbeikor** [comment]
> I dont really know what I'm doing tbh I just wanted to rip some model for a personal project
its not support atm anyways
