### ISSUE TITLE
[Project]:crashing on opening with CryptBase.dll

### ISSUE THREAD

**Issue by GOATv2** [FrostyToolsuite/FrostyToolsuite#37]
### Please describe your issue

game crashing when I place CryptBase into the game directory, i am playing pvz bfn. 

### Were you using the Editor or the Mod Manager?

Editor

### Which version of the Editor/Mod Manager are you using ?

2.0.0

### Has Frosty worked for you before? If so, did anything change ?

.

### Do you have a cracked/pirated version of the game?

No

### Have you extracted all of the zip's contents (files and folders) into an empty folder?

Yes

### Are you using FrostyFix or DatapathFix to fix launching if you didn't purchase the game on Origin?

No

### Which game(s) are you trying to mod?

Plants Vs Zombies Battle For Neighborville

### Which operating system version are you using?

windows 11

### Please provide a breakdown of the steps performed to produce the issue

.

### Please share the FULL error message

.

### If you're using the Mod Manager, have you tried applying only one mod? Did it work?

No

### If you're using the Mod Manager, please list the mods you're applying with

.

### Did you modify, remove, or add any plugins?

No

**Comment by wannkunstbeikor** [comment]
Game has an anti cheat so thats why
